export const HEADER_VERTICAL_PADDING = 10

export const MAIN_HEADER_HEIGHT = 64

export const MAIN_HEADER_HEIGHT_WITH_PADDING =
  MAIN_HEADER_HEIGHT + HEADER_VERTICAL_PADDING * 2

export const DRAWER_WIDTH = 340
